# Generated by Django 3.0.8 on 2020-07-07 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('createalarm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarm',
            old_name='alarm_title',
            new_name='alarm_time',
        ),
        migrations.AddField(
            model_name='alarm',
            name='description',
            field=models.CharField(default=True, max_length=125),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alarm',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=125),
            preserve_default=False,
        ),
    ]
